// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartHire.Infrastructure.Persistence;

#nullable disable

namespace SmartHire.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SmartHireDbContext))]
    [Migration("20261003145328_AddJobIndustries")]
    partial class AddJobIndustries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartHire.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tax_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("verification_status");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_companies");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.CompanyFollow", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "CompanyId")
                        .HasName("pk_company_follows");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("ix_company_follows_company_id");

                    b.ToTable("company_follows", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.CompanyInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("InviteeId")
                        .HasColumnType("uuid")
                        .HasColumnName("invitee_id");

                    b.Property<Guid>("InviterId")
                        .HasColumnType("uuid")
                        .HasColumnName("inviter_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_company_invitations");

                    b.HasIndex("InviteeId")
                        .HasDatabaseName("ix_company_invitations_invitee_id");

                    b.HasIndex("CompanyId", "InviterId")
                        .HasDatabaseName("ix_company_invitations_company_id_inviter_id");

                    b.ToTable("company_invitations", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.CompanyJoinRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_company_join_requests");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_company_join_requests_user_id");

                    b.HasIndex("CompanyId", "ReviewedBy")
                        .HasDatabaseName("ix_company_join_requests_company_id_reviewed_by");

                    b.ToTable("company_join_requests", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.CompanyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_company_memberships");

                    b.HasAlternateKey("CompanyId", "UserId")
                        .HasName("ak_company_memberships_company_id_user_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_company_memberships_user_id");

                    b.ToTable("company_memberships", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.Industry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_industries");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_industries_group_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_industries_name");

                    b.ToTable("industries", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.IndustryGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_industry_groups");

                    b.ToTable("industry_groups", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.JobIndustry", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("IndustryId")
                        .HasColumnType("uuid")
                        .HasColumnName("industry_id");

                    b.HasKey("JobId", "IndustryId")
                        .HasName("pk_job_industries");

                    b.HasIndex("IndustryId")
                        .HasDatabaseName("ix_job_industries_industry_id");

                    b.ToTable("job_industries", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Benefits")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("benefits");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("DetailedLocation")
                        .HasColumnType("text")
                        .HasColumnName("detailed_location");

                    b.Property<string>("EducationLevel")
                        .HasColumnType("text")
                        .HasColumnName("education_level");

                    b.Property<int?>("ExperienceYears")
                        .HasColumnType("integer")
                        .HasColumnName("experience_years");

                    b.Property<string>("JobLevel")
                        .HasColumnType("text")
                        .HasColumnName("job_level");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_type");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("province_id");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("numeric")
                        .HasColumnName("salary_max");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("numeric")
                        .HasColumnName("salary_min");

                    b.Property<bool>("SalaryNegotiable")
                        .HasColumnType("boolean")
                        .HasColumnName("salary_negotiable");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Vacancies")
                        .HasColumnType("integer")
                        .HasColumnName("vacancies");

                    b.Property<Guid?>("WardId")
                        .HasColumnType("uuid")
                        .HasColumnName("ward_id");

                    b.Property<string>("WorkMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_mode");

                    b.HasKey("Id")
                        .HasName("pk_job_postings");

                    b.HasIndex("ProvinceId")
                        .HasDatabaseName("ix_job_postings_province_id");

                    b.HasIndex("WardId")
                        .HasDatabaseName("ix_job_postings_ward_id");

                    b.HasIndex("CompanyId", "CreatedBy")
                        .HasDatabaseName("ix_job_postings_company_id_created_by");

                    b.ToTable("job_postings", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.JobSkill", b =>
                {
                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.HasKey("JobId", "SkillId")
                        .HasName("pk_job_skills");

                    b.HasIndex("SkillId")
                        .HasDatabaseName("ix_job_skills_skill_id");

                    b.ToTable("job_skills", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_provinces");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_provinces_name");

                    b.ToTable("provinces", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_token_hash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_skills_name");

                    b.ToTable("skills", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.Ward", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid")
                        .HasColumnName("province_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_wards");

                    b.HasIndex("ProvinceId")
                        .HasDatabaseName("ix_wards_province_id");

                    b.ToTable("wards", (string)null);
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.CompanyFollow", b =>
                {
                    b.HasOne("SmartHire.Domain.Entities.Company", "Company")
                        .WithMany("Followers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_follows_companies_company_id");

                    b.HasOne("SmartHire.Domain.Entities.User", "User")
                        .WithMany("CompanyFollows")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_follows_users_user_id");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.CompanyInvitation", b =>
                {
                    b.HasOne("SmartHire.Domain.Entities.Company", "Company")
                        .WithMany("Invitations")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_invitations_companies_company_id");

                    b.HasOne("SmartHire.Domain.Entities.User", "Invitee")
                        .WithMany("ReceiveCompanyInvitations")
                        .HasForeignKey("InviteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_invitations_users_invitee_id");

                    b.HasOne("SmartHire.Domain.Entities.CompanyMembership", "Inviter")
                        .WithMany("SendCompanyInvitations")
                        .HasForeignKey("CompanyId", "InviterId")
                        .HasPrincipalKey("CompanyId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_invitations_company_memberships_company_id_inviter_");

                    b.Navigation("Company");

                    b.Navigation("Invitee");

                    b.Navigation("Inviter");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.CompanyJoinRequest", b =>
                {
                    b.HasOne("SmartHire.Domain.Entities.Company", "Company")
                        .WithMany("JoinRequests")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_join_requests_companies_company_id");

                    b.HasOne("SmartHire.Domain.Entities.User", "User")
                        .WithMany("SendCompanyRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_join_requests_users_user_id");

                    b.HasOne("SmartHire.Domain.Entities.CompanyMembership", "Reviewer")
                        .WithMany("ReviewedCompanyJoinRequests")
                        .HasForeignKey("CompanyId", "ReviewedBy")
                        .HasPrincipalKey("CompanyId", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_company_join_requests_company_memberships_company_id_review");

                    b.Navigation("Company");

                    b.Navigation("Reviewer");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.CompanyMembership", b =>
                {
                    b.HasOne("SmartHire.Domain.Entities.Company", "Company")
                        .WithMany("Memberships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_memberships_companies_company_id");

                    b.HasOne("SmartHire.Domain.Entities.User", "User")
                        .WithMany("CompanyMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_company_memberships_users_user_id");

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.Industry", b =>
                {
                    b.HasOne("SmartHire.Domain.Entities.IndustryGroup", "Group")
                        .WithMany("Industries")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_industries_industry_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.JobIndustry", b =>
                {
                    b.HasOne("SmartHire.Domain.Entities.Industry", "Industry")
                        .WithMany("JobIndustries")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_job_industries_industries_industry_id");

                    b.HasOne("SmartHire.Domain.Entities.JobPosting", "Job")
                        .WithMany("JobIndustries")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_industries_job_postings_job_id");

                    b.Navigation("Industry");

                    b.Navigation("Job");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.JobPosting", b =>
                {
                    b.HasOne("SmartHire.Domain.Entities.Company", "Company")
                        .WithMany("JobPostings")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_job_postings_companies_company_id");

                    b.HasOne("SmartHire.Domain.Entities.Province", "Province")
                        .WithMany("JobPostings")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_job_postings_provinces_province_id");

                    b.HasOne("SmartHire.Domain.Entities.Ward", "Ward")
                        .WithMany("JobPostings")
                        .HasForeignKey("WardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_job_postings_wards_ward_id");

                    b.HasOne("SmartHire.Domain.Entities.CompanyMembership", "CreatedByMembership")
                        .WithMany("CreatedJobPostings")
                        .HasForeignKey("CompanyId", "CreatedBy")
                        .HasPrincipalKey("CompanyId", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_job_postings_company_memberships_company_id_created_by");

                    b.Navigation("Company");

                    b.Navigation("CreatedByMembership");

                    b.Navigation("Province");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.JobSkill", b =>
                {
                    b.HasOne("SmartHire.Domain.Entities.JobPosting", "Job")
                        .WithMany("JobSkills")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_skills_job_postings_job_id");

                    b.HasOne("SmartHire.Domain.Entities.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_skills_skills_skill_id");

                    b.Navigation("Job");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("SmartHire.Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("SmartHire.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("SmartHire.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.Ward", b =>
                {
                    b.HasOne("SmartHire.Domain.Entities.Province", "Province")
                        .WithMany("Wards")
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wards_provinces_province_id");

                    b.Navigation("Province");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.Company", b =>
                {
                    b.Navigation("Followers");

                    b.Navigation("Invitations");

                    b.Navigation("JobPostings");

                    b.Navigation("JoinRequests");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.CompanyMembership", b =>
                {
                    b.Navigation("CreatedJobPostings");

                    b.Navigation("ReviewedCompanyJoinRequests");

                    b.Navigation("SendCompanyInvitations");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.Industry", b =>
                {
                    b.Navigation("JobIndustries");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.IndustryGroup", b =>
                {
                    b.Navigation("Industries");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.JobPosting", b =>
                {
                    b.Navigation("JobIndustries");

                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.Province", b =>
                {
                    b.Navigation("JobPostings");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.Skill", b =>
                {
                    b.Navigation("JobSkills");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.User", b =>
                {
                    b.Navigation("CompanyFollows");

                    b.Navigation("CompanyMemberships");

                    b.Navigation("ReceiveCompanyInvitations");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SendCompanyRequests");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("SmartHire.Domain.Entities.Ward", b =>
                {
                    b.Navigation("JobPostings");
                });
#pragma warning restore 612, 618
        }
    }
}
